services:
  app:
    container_name: "bussola-financeira"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-3001}:3001"
      - "5555:5555"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ".env"
    environment:
      - DATABASE_URL_TEST=postgresql://local_user:local_password@database_test:5432/local_db_test?schema=public
    depends_on:
      database_dev:
        condition: service_healthy
      database_test:
        condition: service_healthy

  database_dev:
    container_name: "postgres-dev"
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-local_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-local_password}
      POSTGRES_DB: ${POSTGRES_DB:-local_db}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-local_user} -d ${POSTGRES_DB:-local_db}",
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  database_test:
    container_name: "postgres_test"
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_USER: local_user
      POSTGRES_PASSWORD: local_password
      POSTGRES_DB: local_db_test
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U local_user -d local_db_test"]
      interval: 10s
      timeout: 5s
      retries: 5
