services:
  database_dev:
    container_name: "postgres-dev"
    image: "postgres:16.0-alpine3.18"
    env_file:
      - ".env"
    ports:
      - "5432:5432"
  database_test:
    container_name: "postgres_test"
    image: "postgres:16.0-alpine3.18"
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TEST}
      POSTGRES_USER: ${POSTGRES_USER_TEST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST}
    ports:
      - "5433:5432"
